android-pixel-7-superwall:
  type: instrumentation
  use-orchestrator: true
  test: superwall/build/outputs/apk/androidTest/debug/superwall-debug-androidTest.apk
  directories-to-pull: /sdcard/Download/
  device:
    - model: panther
      version: 33
      locale: 'en'
      orientation: portrait