android-pixel-7:
  type: instrumentation
  use-orchestrator: true
  app: app/build/outputs/apk/debug/app-debug.apk
  test: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  directories-to-pull: /sdcard/Download/
  device:
    - model: panther
      version: 33
      locale: 'en'
      orientation: portrait