appId: com.superwall.superapp

flows:
  # Main flow tests
  - flow.yaml
  
  # Delegate tests
  - delegate/flow.yaml
  
  # Handler tests  
  - handler/flow.yaml
  
  # Purchase controller tests
  - purchasecontroller/no_pc_purchases.yaml
  - purchasecontroller/test_pc_purchases.yaml

env:
  PLATFORM_ID: com.superwall.superapp
  
# Test execution settings
continueOnFailure: false